[package]
name = "gramma"
version = "0.1.0"
authors = ["Spencer Young <spencerwyoung@outlook.com>"]
edition = "2018"
repository = "https://github.com/youngspe/gramma"
license-file = "LICENSE"
description = "A library for defining typed CFG parsers with arbitrary lookahead."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
regex = "1.4"
smallvec = "1.6"
thiserror = "1.0"
